POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY2NWVlMmJiZDQzMTJkMTA3NWZlMDJhNiIsImlhdCI6MTcxNzUwNjg0NH0.YVvO58HIBdGxUZEjXqyn6lW3saRXQKyAufT73HEXeiU

{
    "title": "Title",
    "author": "Athuor",
    "url": "anurl.com",
    "likes": 5
}